### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by gbonnefille** [MarkusFreitag/keepassxc-go#8]
It would be usefull to have support for windows platform.

**Comment by gbonnefille** [comment]
While Unix and macOS use Unix socket, Windows uses named pipes (https://github.com/keepassxreboot/keepassxc/blob/2.6.0/src/browser/BrowserShared.cpp#L30).

Looking at the code, it seems that the code should be refactored in order to replace the function `SocketPath` giving the UNIX socket's path by a function (`Socket`?) giving directly the `net.Conn` socket.

An implementation example can be find in https://github.com/xakep666/gkpxc

Are you interested in such change?
I think I can try a PR, but something in the end of the week.

**Comment by MarkusFreitag** [comment]
Yes feel free to open a PR, I'm open for contributions. Changing the architecture related code, so it directly returns the socket would be fine.
